version: '3.1'

services:
  app:
    build: .
    ports:
      - "8086:8086"
    depends_on:
      - db
    environment:
      DB_URL: jdbc:mysql://db:3307/errorDb
    restart: on-failure
    networks:
      - global-network

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 'marcoroot'
      MYSQL_DATABASE: errorDb
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10